# Thesis work--1

### Importing the libraries

In [144]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from random import randrange, uniform

### Global variables and functions for tuning

In [145]:
FEATURES = 4
ROWS = 10
LOW_RANGE = 0
HIGH_RANGE = 10
SELECTION_X_GENERATOR = ['random_normal_dist','random_normal_range','set_manual_x']
SELECTED_GENERATOR = SELECTION_X_GENERATOR[1]
APPLY_FEATURE_SCALING = False
formula = lambda X: X[:,2] - X[:,0] + 5*X[:,1]**2 + (abs(X[:,3])*100)**2

### Generating random numbers using normal distribution

In [146]:
def rnd_norm():
    X = []
    for itr in range(FEATURES):
        X.append(np.random.normal(size=ROWS))
    X = np.asarray(X)
    X = X.reshape(ROWS,FEATURES)
    return X
    

### GENERATE NUMBER USING RANGES 

In [147]:
def rnd_rng():
    X = []
    for feat_ in range(FEATURES):
        temp_ = []
        for rows_ in range(ROWS):
            temp_.append(uniform(LOW_RANGE, HIGH_RANGE))
        X.append(temp_)
        temp_ = []
    X = np.asarray(X)
    X = X.reshape(ROWS,FEATURES)
    return X

### MANUALLY SET X

In [148]:
def mnl_x():
    X = [[4.77483186, 3.39440415, 57.05801446, 6.71629158],
 [6.61347886, 7.2255493,  122.77241787, 7.31532667],
 [4.5746061,  6.94376097, 1.57398063, 7.61596309],
 [3.99442041, 7.74271857, -22.18103276, 8.69864701],
 [7.74195296, 8.66056046, 1000.71418768, 8.66512174],
 [0.70227095, 8.48112974, 12.18087887, 9.98354661],
 [3.30624855, 1.28647579, 29.10406468, 8.96630542],
 [5.7062847,  7.72417331, 56.45891841, 5.15614429],
 [3.70369596, 1.79230683, 157.60607582, 9.4736015 ],
 [5.36628365, 9.68201719, 888.00342486, 2.75472882]]
    X = np.asarray(X)
    return X

### SELECT GENERATION METHOD

In [149]:
if 'random_normal_dist' == SELECTED_GENERATOR:
    X = rnd_norm()
elif 'random_normal_range' == SELECTED_GENERATOR:
    X = rnd_rng()
elif 'set_manual_x' == SELECTED_GENERATOR:
    X = mnl_x()

### Generating random numbers Y

In [150]:
Y = formula(X)
print(np.shape(Y))
print(Y)

(10,)
[427847.46023991  32214.58915217  67365.61700837 847049.83155207
  65541.08960479  97518.17694715 133289.67973698 296317.99202436
  32159.95868934 140768.24283422]


### Splitting the dataset into the Training set and Test set

In [151]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [152]:
from sklearn.preprocessing import StandardScaler
if APPLY_FEATURE_SCALING:
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)

### Applying PCA

In [160]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 1)
print(X_train)
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)
explained_variance = pca.explained_variance_ratio_
print(X_train_pca)
print(X_test_pca)
# print(np.shape(X_train),np.shape(X_test))
print(explained_variance)

[[0.53774486 9.49273557 1.2716799  2.55127018]
 [1.54642689 0.60882226 0.46852903 3.75189908]
 [3.36575131 1.93161878 3.64738687 1.79431468]
 [1.21212386 7.72467462 6.32183733 3.64672753]
 [6.63684924 6.91567964 3.9460461  5.44133761]
 [3.84910159 7.69052357 5.1389027  9.20191731]
 [3.94653461 6.67357544 1.93778794 6.5393179 ]
 [1.28423668 8.48104303 9.61317545 3.1168928 ]]
[[-0.4867446 ]
 [ 6.5765848 ]
 [ 3.9717073 ]
 [-2.48111085]
 [-0.55800107]
 [-2.6238301 ]
 [ 0.62245206]
 [-5.02105753]]
[[0.52550755]
 [1.68436255]]
[0.48209874]


### Applying LDA

In [161]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
# lda = LDA(n_components = None)
# X_train_lda = lda.fit_transform(X_train, y_train)
# X_test_lda = lda.transform(X_test)

### Applying Kernel PCA

In [156]:
from sklearn.decomposition import KernelPCA
kpca = KernelPCA(n_components = 2, kernel = 'rbf')
X_train_pca = kpca.fit_transform(X_train)
X_test_pca = kpca.transform(X_test)

### Applying without hard points

In [ ]:
error = 0 
